services:
  web:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: ${DOCKER_NAME}_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./service:/var/www/html
      - /var/www/html/application/files/cache
      - /var/www/html/application/config/doctrine
      - /var/www/html/application/config/generated_overrides
      - ./docker/apache2/sites-available:/etc/apache2/sites-available:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    ports:
      - 8090:80
    networks:
      - aeestarreja

  mysql-db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - '3310:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: ['--mysql-native-password=ON']
    container_name: ${DOCKER_NAME}_db
    networks:
      - aeestarreja

networks:
  aeestarreja: